[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
Vegas = "fa56aa31-9f07-5578-a677-b1eb73889b05"

[sources]
Vegas = {path = "/Users/uwe/Work/jlProjects/QEDjl-project/forks/Vegas.jl/docs/.."}

[compat]
Documenter = "1"
